### ISSUE TITLE
How do you feel about creating a dataset for plex_data?

### ISSUE THREAD

**Issue by thorsteneb** [danb35/freenas-iocage-plex#4]
Your script currently makes a directory if a dataset matching PLEX_CONFIG_PATH doesn't exist. How do you feel about creating the dataset instead? Or would you rather leave that as a deliberate action for the user, outside the script?

**Comment by danb35** [comment]
I remember discussing this previously, probably with Basil on one of the forum threads.  No, I don't want to be creating datasets in the script--if the user wants PLEX_CONFIG_PATH to be its own dataset, the user will need to create that dataset first.  I did recently update the README to discuss this, though.
