### ISSUE TITLE
Enable modifying the uid and gid that the plex user runs as

### ISSUE THREAD

**Issue by YodaDaCoda** [danb35/freenas-iocage-plex#8]
I have my media readable to group `media` with gid `1000`. It'd help to add something to either change the default user's group, or add a new group and attribute it to the default user.

```
# change the gid of the plex group
pw groupmod plex -n plex -g $GID
# change the uid of the plex user, and ensure they're linked to the correct group
pw usermod plex -n plex -u $UID -g $GID
# take ownership of the plex user's config files
chown -R plex:plex /config
```

**Comment by danb35** [comment]
I don't think I'd be inclined to be changing the UID/GID for the plex user/group respectively--those are set by the package installation, and they're expected to be what they're set to.  However, either of these might help:

* Add the plex user to a secondary group (generally your `media` group)
* Configure Plex to run as a different user (though that would also involve creating that user in the jail).

**Comment by YodaDaCoda** [comment]
[This guide](https://www.ixsystems.com/community/resources/fn11-3-iocage-jails-plex-tautulli-sonarr-radarr-lidarr-jackett-transmission-organizr.58/) has setup scripts for a number of different applications including Plex. While its Plex guide doesn't include modifying the user, most of the other guides do. Turns out that if the user that the package creates upon installation already exists, it's just used as-is. This means you can create a `plex` user with the requisite uid/gid before package installation, and it'll Just Work :tm:. It's certainly working for me without issue.

```
SERVICE_USER=plex
SERVICE_USER_ID=1000
SERVICE_GROUP=plex
SERVICE_GROUP_ID=1000
pw group add "${SERVICE_GROUP}" -g "${SERVICE_GROUP_ID}"
pw user add "${SERVICE_USER}" -u "${SERVICE_USER_ID}" -g "${SERVICE_GROUP_ID}" -d /nonexistent -s /usr/bin/nologin
```

**Comment by YodaDaCoda** [comment]
I also want `plex` to be uid 1000. Which I can achieve by executing the appropriate commands, sure, but it helps to create the user as required rather than modifying the user and running `chown` on a bunch of stuff.

**Comment by YodaDaCoda** [comment]
Thank you for your opinion.
